// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3xgqzBcxSPQ2XnFQ3WHkiHnC77cqu16A',
    appId: '1:192406267687:web:c00ccb4c91958e56fd6b02',
    messagingSenderId: '192406267687',
    projectId: 'burgir-app',
    authDomain: 'burgir-app.firebaseapp.com',
    storageBucket: 'burgir-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKv9yAgC7wYM3xOPdHml21PfE6w8zrEEk',
    appId: '1:192406267687:android:03a76fe7ca509a79fd6b02',
    messagingSenderId: '192406267687',
    projectId: 'burgir-app',
    storageBucket: 'burgir-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQMuttNj_JHIbd4alnu2uAdhW2OPfGZgc',
    appId: '1:192406267687:ios:5e6f815758f1a88ffd6b02',
    messagingSenderId: '192406267687',
    projectId: 'burgir-app',
    storageBucket: 'burgir-app.appspot.com',
    iosClientId: '192406267687-8dmdu1irj3djn5r6nf1nbnha2uhpaen2.apps.googleusercontent.com',
    iosBundleId: 'com.burgir.app',
  );
}
